### ISSUE TITLE
mergeSortedFiles with BufferedWriter cannot be used

### ISSUE THREAD

**Issue by wavyx** [lemire/externalsortinginjava#20]
I'm trying to use the merge method with a GZIPOutput Buffered writer.
The method mergeSortedFiles(BufferedWriter fbw, final Comparator<String> cmp, boolean distinct, List<BinaryFileBuffer> buffers) looks perfect, but the dependency to BinaryFileBuffer makes it impossible to use.
As BinaryFileBuffer is a non-public child class, you cannot use it externally and you cannot extend it either.
Could you just make the BinaryFileBuffer a standard public class in its own file?

Thanks

**Comment by wavyx** [comment]
Well it looks fixed in 0.3.0
But I'm still relying on 0.2.5 as it was not bumped in maven repository https://search.maven.org/search?q=g:com.google.code.externalsortinginjava%20AND%20a:externalsortinginjava

**Comment by lemire** [comment]
The maven repo is a bit finicky, let us try to issue a new release.

**Comment by lemire** [comment]
We had to disable javadoc due to a long-standing bug preventing releases with recent JDKs, but otherwise, version 0.3.1 should appear on the maven repo.

**Comment by wavyx** [comment]
Thanks for the new release, but it looks like it's still not visible in maven repo :'( 
https://repo.maven.apache.org/maven2/com/google/code/externalsortinginjava/externalsortinginjava/

**Comment by lemire** [comment]
I think you have to be patient. In my experience, it can take up to 48 hours. If it does not get resolved in the next 36 hours, please ping me.

*I* did the release, I have the commit logs to prove it. There were no error that I could see on my end.

**Comment by lemire** [comment]
> Indeed I thought it was almost "realtime".

You would think so, wouldn't you? Sometimes it appears right away, sometimes there is a long delay. There seems to be no reason for it all.

It is very frustrating. It means that there is no way to verify that it worked after releasing the command... you have to wait...
