### ISSUE TITLE
ExternalSort.sortInBatch returns empty file, ExternalSort.mergeSortedFiles doesn't delete it

### ISSUE THREAD

**Issue by agherardi** [lemire/externalsortinginjava#21]
I have a test that call ExternalSort.sortInBatch with a very small maxMemory - 100 bytes. When I call that method on a small file, ExternalSort.sortInBatch creates 5 temporary files, one of which is empty. I then call ExternalSort.mergeSortedFiles on the result of ExternalSort.sortInBatch. The resulting merged file is correct, however ExternalSort.mergeSortedFiles  doesn't delete the empty file.

That seems to be caused by the empty file still being in use (I'm running on Windows). The code only adds non-empty files to the priority queue:

`

           public static long mergeSortedFiles(BufferedWriter fbw,
                final Comparator<String> cmp, boolean distinct,
                List<IOStringStack> buffers)  ...
                for (IOStringStack bfb : buffers) {
                        if (!bfb.empty()) {
                                pq.add(bfb);
                        }
                }
`
Since the empty file is not on the queue, it's not being closed so it cannot be deleted.

There is probably more than one way to fix this issue - e.g., if a file is empty, don't create an IOStringStack for it. I'm not sure what's the best way.

**Comment by lemire** [comment]
Thanks for the report.

**Comment by agherardi** [comment]
See https://github.com/lemire/externalsortinginjava/pull/22

**Comment by agherardi** [comment]
You're welcome

**Comment by lemire** [comment]
I'll issue a release.
