### ISSUE TITLE
Output file is same as input file. NO Change

### ISSUE THREAD

**Issue by kapil-signity** [lemire/externalsortinginjava#34]
I have a csv file with float value in first column. I run the program but output file is same as input file.
Here is my code:-

```
Comparator<CSVRecord> comparator = (op1, op2) -> op1.get(0).compareTo(op2.get(0));
        File inputFile=new File("/home/signity/Documents/workshop/csvjobmultiplier/TEMP_DIR/test/short.csv");
        File outputfile=new File("/home/signity/Documents/workshop/csvjobmultiplier/TEMP_DIR/test/output_ks.csv");
        CsvSortOptions sortOptions = new CsvSortOptions
                .Builder(comparator, CsvExternalSort.DEFAULTMAXTEMPFILES, CsvExternalSort.estimateAvailableMemory())
                .charset(Charset.defaultCharset())
                .distinct(false)
                .numHeader(0)
                .skipHeader(false)
                .format(CSVFormat.DEFAULT)
                .build();
        ArrayList<CSVRecord> header = new ArrayList<CSVRecord>();
        List<File> sortInBatch = CsvExternalSort.sortInBatch(inputFile, null, sortOptions, header);
        CsvExternalSort.mergeSortedFiles(sortInBatch, outputfile, sortOptions, true, header);
```

**INPUT CSV FILE SYNTAX:-**

> 0.3,0.3,"39826ab68245a00e85853fb04d337c17",TRUE
> 10,10,"39826ab68245a00e85853fb04d337c17",TRUE
> 10,10,"39826ab68245a00e85853fb04d337c17",TRUE
> 126,126,"39826ab68245a00e85853fb04d337c17",TRUE
> 126,126,"39826ab68245a00e85853fb04d337c17",TRUE
> 126,126,"39826ab68245a00e85853fb04d337c17",TRUE
> 17,17,"39826ab68245a00e85853fb04d337c17",TRUE
> 2,2,"39826ab68245a00e85853fb04d337c17",TRUE
> 2,2,"39826ab68245a00e85853fb04d337c17",TRUE
> 21,21,"39826ab68245a00e85853fb04d337c17",TRUE
> 22,22,"39826ab68245a00e85853fb04d337c17",TRUE
> 233,233,"39826ab68245a00e85853fb04d337c17",TRUE
> 233,233,"39826ab68245a00e85853fb04d337c17",TRUE
> 233,233,"39826ab68245a00e85853fb04d337c17",TRUE

**OUTPUT CSV FILE (NO CHANGE):-**

> 0.3,0.3,"39826ab68245a00e85853fb04d337c17",TRUE
> 10,10,"39826ab68245a00e85853fb04d337c17",TRUE
> 10,10,"39826ab68245a00e85853fb04d337c17",TRUE
> 126,126,"39826ab68245a00e85853fb04d337c17",TRUE
> 126,126,"39826ab68245a00e85853fb04d337c17",TRUE
> 126,126,"39826ab68245a00e85853fb04d337c17",TRUE
> 17,17,"39826ab68245a00e85853fb04d337c17",TRUE
> 2,2,"39826ab68245a00e85853fb04d337c17",TRUE
> 2,2,"39826ab68245a00e85853fb04d337c17",TRUE
> 21,21,"39826ab68245a00e85853fb04d337c17",TRUE
> 22,22,"39826ab68245a00e85853fb04d337c17",TRUE
> 233,233,"39826ab68245a00e85853fb04d337c17",TRUE
> 233,233,"39826ab68245a00e85853fb04d337c17",TRUE
> 233,233,"39826ab68245a00e85853fb04d337c17",TRUE

**Comment by lemire** [comment]
Let us look at your comparator:
```java
Comparator<CSVRecord> comparator = (op1, op2) -> op1.get(0).compareTo(op2.get(0));
```

If I read this read, you are recovering the first element of each row as `java.lang.String`, and comparing them two-by-two as strings. So you should get "0.3", "10", "126", "17", etc. as you can verify...

<img width="422" alt="Screen Shot 2020-10-07 at 3 17 47 PM" src="https://user-images.githubusercontent.com/391987/95377221-446a1000-08b0-11eb-8085-0e254c60adf4.png">

Hence, it seems that your input is already in sorted order.

> Output file is same as input file. NO Change

So before opening this issue and describing it as the function producing no change, you surely tried many different ordering of the input, correct ? 

Do I understand you correctly, that no matter what input your provide, there is no change to the output? If so, please reopen a new issue with a test case.

**Comment by kapil-signity** [comment]
@lemire Thank you. I understand the point you said. Now Same code is working.
