### ISSUE TITLE
Sort CSV based on multiple columns

### ISSUE THREAD

**Issue by abhinandanmadaan** [lemire/externalsortinginjava#35]
**1. Is it possible to sort a CSV file based on multiple columns, say firstName, lastName, and dob?** 
For example in case multiple records have the same firstName, those records will be sorted based on the lastName value. If lastName is also same, they will be sorted based on the dob value, And so on.

**2. Can this method also be applied to sort fixed length files based on multiple columns?**

If yes, can you point me to where can I find some samples of those?

**Comment by lemire** [comment]
> 1. Is it possible to sort a CSV file based on multiple columns, say firstName, lastName, and dob?

Yes.  You have to implement the corresponding operator, see our example at:
https://github.com/lemire/externalsortinginjava#code-sample-csv


> 2. Can this method also be applied to sort fixed length files based on multiple columns?


I am not sure what a fixed-length CSV file is. You must mean something else.

In any case, you can sort any file made of lines of strings (e.g., not CSV files), you just have to provide your own comparator.

> If yes, can you point me to where can I find some samples of those?

We do not have more examples, however you are welcome to provide additional examples (pull requests invited).

**Comment by abhinandanmadaan** [comment]
> Yes. You have to implement the corresponding operator, see our example at:

I'm not sure what you are referring to by **_corresponding operator_**. I tried creating a custom comparator but it required me to map the csv columns to corresponding POJO object, **in order to sort based on multiple columns.** I'm sure there is a better way to achieve this.

> I am not sure what a fixed-length CSV file is. You must mean something else.
> In any case, you can sort any file made of lines of strings (e.g., not CSV files), you just have to provide your own comparator.

- Unlike CSV files, fixed length/width files are not delimited files. 

- Fixed width text files are special cases of text files where the format is specified by column widths, pad character and left/right alignment.  Column widths are measured in units of characters. For example, if you have data in a text file where the first column always has exactly 10 characters, and the second column has exactly 5, the third has exactly 12 (and so on), this would be categorized as a fixed width text file.

- No delimiters are used to separate the fields in the file.  Instead, smaller quantities of data are padded with spaces to fill the allotted space, such that the start of a given column can always be specified as an offset from the beginning of a line.

Example of a fixed length file can be seen [here](https://www.softinterface.com/Convert-XLS/Features/Fixed-Width-Text-File-Definition.htm#:~:text=For%20example%2C%20if%20you%20have,a%20fixed%20width%20text%20file.&text=Each%20row%20contains%20one%20or,to%20as%20columns%20or%20fields)

**Comment by lemire** [comment]
>I'm not sure what you are referring to by corresponding operator. I tried creating a custom comparator but it required me to map the csv columns to corresponding POJO object, in order to sort based on multiple columns. 



You have to implement a `Comparator<CSVRecord>` comparator. You are given two CSVRecord and must compare them. 

> I'm sure there is a better way to achieve this.

Can you elaborate? Better than what? Better than providing your `Comparator<CSVRecord>` comparator?


Regarding the rest of your question, the answer is the same. You can provide your own `Comparator<String>` comparator. It does not matter to the library what is stored in the string. You just have to write the comparator. You can use substring to access fields, for example... it is up to you.

**Comment by lemire** [comment]
I am going to close this. The way this library works is by asking the developers to provide their own comparator. I do not think we will change this API. It is flexible and generally viewed as convenient. You can write a comparator using a few lines of code.

It is true that we do not provide many examples. You are invited to propose a pull request with more elaborate use-case examples. It would be a great contribution.
