### ISSUE TITLE
What is numHeader and skipHeader?

### ISSUE THREAD

**Issue by abhinandanmadaan** [lemire/externalsortinginjava#36]
I was a bit confused with the skipheader and numHeader in the the CSVSortOptions.
Couldn't find the description in your API documentation.
Can you please elaborate?

**Comment by lemire** [comment]
I believe that it is the number of lines of headers in the CSV files (typically 1 or 0) and whether you would like to exclude them from the parsing.

**Comment by lemire** [comment]
The documentation could be improved generally. Pull requests are invited.

**Comment by abhinandanmadaan** [comment]
After a few trials I've found out the following:
Assuming it is set as `.numHeader(n)`. This implies the first `n` lines of the input file won't be parsed.
And `.skipHeader(true)` means those first `n` unparsed lines won't be written to the output file.
`.skipHeader(false)` means those first `n` unparsed lines would be printed in the output file as it is.

So `numHeader` is more related to the `inputFile` and its parsing.. While `skipHeader` is more related to if they need to be written to the output file

**Comment by lemire** [comment]
@abhinandanmadaan I believe that what you wrote is correct.
