### ISSUE TITLE
Update commons-csv to 1.9.0

### ISSUE THREAD

**Issue by evgenydatanerds** [lemire/externalsortinginjava#38]
I'm using org.apache.commons:commons-csv:1.9.0
Could we update it in externalsortinginjava ?
So when I have commons-csv:1.9.0 running in runtime, I know that externalsortinginjava was compiled against 1.9 as well.

**Comment by lemire** [comment]
Would you be willing to propose a pull request?

**Comment by evgenydatanerds** [comment]
Yes, but looks like I don't have permissions to create branch.

**Comment by lemire** [comment]
@evgenydatanerds You must first create a fork.

https://reflectoring.io/github-fork-and-pull/

**Comment by evgenydatanerds** [comment]
https://github.com/lemire/externalsortinginjava/pull/39

**Comment by lemire** [comment]
Released.
