### ISSUE TITLE
CsvExternalSort.mergeSortedFiles rowcounter when sortOptions.isDistinct()

### ISSUE THREAD

**Issue by julianSelser** [lemire/externalsortinginjava#46]
Hi, thanks for this great library!

I've noticed `CsvExternalSort.mergeSortedFiles()` counts all rows even when `sortOptions.isDistinct()` and was wondering if this is on purpose, I expected it to return the number of rows in the sorted file.

I can already count the number of rows in the input but Im forced to reopen the output file and count myself otherwise. There is no test for `distinct(true)` on [CsvExternalSortTest.java](https://github.com/lemire/externalsortinginjava/blob/54bd7b46773f81628470cffd6eb2eca46ede7292/src/test/java/com/google/code/externalsorting/csv/CsvExternalSortTest.java) so Im not sure.

Seems like we could move the counter next to `printRecord()` in [mergeSortedFiles](https://github.com/lemire/externalsortinginjava/blob/54bd7b46773f81628470cffd6eb2eca46ede7292/src/main/java/com/google/code/externalsorting/csv/CsvExternalSort.java#L73) like this?
```
if (sortOptions.isDistinct() && checkDuplicateLine(r, lastLine)) {
} else {
	printer.printRecord(r);
	++rowcounter;
	lastLine = r;
}
```

We'd find the feature really useful, let me know if its ok to submit a PR regarding the above or if we could discuss a way to include it that makes sense if this doesnt. Thanks!

**Comment by lemire** [comment]
Pull request invited !!!

**Comment by julianSelser** [comment]
Awesome! Here is a PR: https://github.com/lemire/externalsortinginjava/pull/47

**Comment by julianSelser** [comment]
Nice! Looking forward to the new version in maven central to pull the update, thanks again!

**Comment by julianSelser** [comment]
@lemire quick question, do I need to do something to upload the artifact to maven central?

**Comment by lemire** [comment]
Maven central is slow. It can take days or weeks for the artefacts to appear. It is not a serious platform.

They have been updated, there is nothing more to do but wait.

**Comment by lemire** [comment]
It did appear earlier today.

https://repo1.maven.org/maven2/com/google/code/externalsortinginjava/externalsortinginjava/0.6.2/
