### ISSUE TITLE
performance for external sorter

### ISSUE THREAD

**Issue by patelprateek** [lemire/externalsortinginjava#48]
Thanks for this module .
I was wondering if you have any information regarding how the performance of this module would be when using SSDs  vs sayy using a rocksDB embedded KV store that relies on SST files. 

if i don't want to take a dependency on rocksdb this library makes perfect use case for me , but wondering if its more performant , wanted to use it for some streaming ingesting use cases with low latency requirement,

**Comment by lemire** [comment]
@patelprateek Why not write a benchmark?

It is very difficult in the abstract to predict the performance of a piece of code against another piece of code in an unknown setting with unknown data.
