### ISSUE TITLE
Encryption of Data at Rest

### ISSUE THREAD

**Issue by afishcalledrob** [lemire/externalsortinginjava#49]
Does this library currently have the ability to support encryption of data at rest (ie: disc)?

**Comment by lemire** [comment]
Can you elaborate?

**Comment by afishcalledrob** [comment]
If one were using this as part of a sorting algorithm does it have the capability to handle data securely by encrypting it before it is written to disk and decrypting it when it is read back into memory?

**Comment by lemire** [comment]
The library uses standard java file IO. If you disk is encrypted, the operating system will encrypt and decrypt as needed.
