### ISSUE TITLE
ExternalSort.sortInBatch - java.io.IOException: The system cannot find the path specified

### ISSUE THREAD

**Issue by GelukkigTurtle** [lemire/externalsortinginjava#8]
Hi,

I used to work with this library on Linux but now when i work in windows throw me this exception java.ioException. I verified the paths and there are OK. If i am doing something wrong, please tell me. 

Thank in advance

This is my code:

`
```
def sortFile(inputFile: String, outputFile: String): Int = {
    logger.info("sorting file " + inputFile)
    logger.info("sorted file " + outputFile)

    val distinct = true
    val maxtmpfiles = 1024
    val cs = java.nio.charset.Charset.defaultCharset()
    val tempFileStore: File = new File(outputFile)
    val usegzip = false
    val headersize = 0
    var response = 0
    try {

      val comparator = ExternalSort.defaultcomparator

      val fileToSort = new File(inputFile)
      val fileSorted = new File(outputFile)

      if (!fileToSort.exists()) {
        logger.error("File Not found " + inputFile)
      }

      val l = ExternalSort.sortInBatch(fileToSort, comparator,
        maxtmpfiles, cs, tempFileStore, distinct, headersize, usegzip) //This is the line 204 that cause the exception 

      if (!fileSorted.exists()) {
        logger.error("File not found " + outputFile)
      }

      response = ExternalSort.mergeSortedFiles(l, fileSorted, comparator, cs,
        distinct, false, usegzip)


    } catch {
      case e: Exception => {
        logger.error("Error sorting", e)
      }
    }
    response
  }
```
`

And this the Log output:

`sorting file C:\subscriber-files\main-prepago.csv
sorted file C:\subscriber-files\sorted-main-prepago.csv
Error sorting java.io.IOException: The system cannot find the path specified
	at java.io.WinNTFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_65]
	at java.io.File.createTempFile(File.java:2024) ~[?:1.8.0_65]
	at com.google.code.externalsorting.ExternalSort.sortAndSave(ExternalSort.java:465) ~[externalsortinginjava-0.1.9.jar:?]
	at com.google.code.externalsorting.ExternalSort.sortInBatch(ExternalSort.java:594) ~[externalsortinginjava-0.1.9.jar:?]
	at com.google.code.externalsorting.ExternalSort.sortInBatch(ExternalSort.java:731) ~[externalsortinginjava-0.1.9.jar:?]
	at subscriberdumper.utils.FileUtils$.sortFile(Utils.scala:204) [subscribers-dumper-1.0-SNAPSHOT.jar:?]
`

**Comment by lemire** [comment]
This line...

     val l = ExternalSort.sortInBatch(fileToSort, comparator,
        maxtmpfiles, cs, tempFileStore, distinct, headersize, usegzip) 

assumes that ``tempFileStore`` is the temporary where you put temporary files. Are you sure that this is a valid directory? Try passing the null value instead...

     val l = ExternalSort.sortInBatch(fileToSort, comparator,
        maxtmpfiles, cs, null, distinct, headersize, usegzip)

**Comment by hansenmc** [comment]
It appears that you have created a File object for the temp dir using the `outputFile` path. 

You should be specifying the path to a **Directory**, not a **File**, for the `tempFileStore`. You could try using the parent directory of your outputFile: `val tempFileStore: File = new File(outputFile).getParent();`, or create a tempDir and pass it's path.

Or, if you set it to `null`, as @lemire suggested, then the default Java temp dir will be used.

**Comment by lemire** [comment]
Given @hansenmc's excellent explanation, I am going to close this. Reopen if you still think that there is a problem.

**Comment by GelukkigTurtle** [comment]
Thank you guys! Problem resolved!
