### ISSUE TITLE
maxtmpfiles comparison.

### ISSUE THREAD

**Issue by feyyazesat** [lemire/externalsortinginjava#9]
https://github.com/lemire/externalsortinginjava/blob/master/src/main/java/com/google/code/externalsorting/ExternalSort.java#L146
Shouldn't be there like following instead of `headersize` ?
```java
                if (maxtmpfiles < 0) {
                        System.err
                                .println("maxtmpfiles should be positive");
                }
```

**Comment by lemire** [comment]
Yes, it is a typo. Do you want to issue a PR?

**Comment by feyyazesat** [comment]
was a little issue, I opened the PR, thanks 👍

**Comment by lemire** [comment]
+1
